### ISSUE TITLE
Upgrade fly action from version `v1.0.0` to `v1.1.0`

### ISSUE THREAD

**Issue by userbradley** [Qoyyuum/buymeacoffee-integration#1]
Howdy,

A version has been released to the fly action you're using

https://github.com/userbradley/actions-fly

```yaml
name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  site:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
      - name: Build and deploy 
        uses: userbradley/actions-fly@v1.1.0
        with:
          flyToken: ${{ secrets.FLY_ACCESS_TOKEN_DEV }}
```

You dont need to specify fly config file or Dockerfile as you're using the default values from what I can see
